// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8XVTGb51AwIo8M8Cq1kqSi3DsStLqGIw',
    appId: '1:217660479758:web:c9676349f4ac37f5cddf5f',
    messagingSenderId: '217660479758',
    projectId: 'liveinbuddy-a4cc5',
    authDomain: 'liveinbuddy-a4cc5.firebaseapp.com',
    storageBucket: 'liveinbuddy-a4cc5.firebasestorage.app',
    measurementId: 'G-SHZHLT8D5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70mj9lWjHAdNolnZo15PsdjchsI6oQGw',
    appId: '1:217660479758:android:09c2ff66ae976ecccddf5f',
    messagingSenderId: '217660479758',
    projectId: 'liveinbuddy-a4cc5',
    storageBucket: 'liveinbuddy-a4cc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_CPefCj2LeTfiYbMwEAK0dhTFwKLn48',
    appId: '1:217660479758:ios:52847c78d4a0c9e2cddf5f',
    messagingSenderId: '217660479758',
    projectId: 'liveinbuddy-a4cc5',
    storageBucket: 'liveinbuddy-a4cc5.firebasestorage.app',
    iosBundleId: 'com.example.liveinFiras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_CPefCj2LeTfiYbMwEAK0dhTFwKLn48',
    appId: '1:217660479758:ios:49ec562ad5ae9c39cddf5f',
    messagingSenderId: '217660479758',
    projectId: 'liveinbuddy-a4cc5',
    storageBucket: 'liveinbuddy-a4cc5.firebasestorage.app',
    iosBundleId: 'com.example.livein',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8XVTGb51AwIo8M8Cq1kqSi3DsStLqGIw',
    appId: '1:217660479758:web:27413d22cfcfae8ccddf5f',
    messagingSenderId: '217660479758',
    projectId: 'liveinbuddy-a4cc5',
    authDomain: 'liveinbuddy-a4cc5.firebaseapp.com',
    storageBucket: 'liveinbuddy-a4cc5.firebasestorage.app',
    measurementId: 'G-CK1CGB37F5',
  );
}
